server:
  port: 9254
spring:
 datasource:
#    url: jdbc:mysql://112.125.92.183:3306/machao01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/machao01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
 redis:
   host: 112.125.92.183
   password: Wwl145869
   port: 6379
#Mybatis配置信息映射文件，及pojo类所在包路径
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.dci.pojo
logging:
  file:
    name: logs/machao.log
